@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

'LAYOUT_WITH_LEGEND()

title Диаграмма компонентов Модуля наблюдения за животными
Container(ШУ, "Шлюз уведомлений (ШУ)")
Container(ИИ, "Модуль ИИ")
Container(GW, "API Шлюз")
ContainerDb(ПМА_БД, "База данных ПМА")
Container(БС, "Брокер сообщений (БС)")

Container_Boundary(api, "Модуль наблюдения за животными") {
    Component(СПС, "Сервис получения событий в системе", "gRPC API", "Точка входа обработки событий")
    Component(СОС, "Сервис обработки событий", "Service", "Обрабатывает событие, принимает решение о необходимости отправить уведомление, синхронизировать данные с ЦС")
    Component(ra, "REST API")
    Component(СИЖ, "Сервис информации о животных")
    Component(Р, "Репозиторий БД")
    Component(КИБС, "Компонент интеграции с БС")
    Component(КУ, "Компонент уведомлений")

    Rel_D(СИЖ, Р, "Использует", "Java API")
    Rel(Р, ПМА_БД, "Использует", "JDBC")
    Rel(СПС, СОС, "Передает событие для обработки", "Java API")
    Rel_R(СОС, СИЖ, "Использует", "Java API")
    Rel(СОС, КИБС, "Использует", "Java API")
    Rel(СОС, КУ, "Использует", "Java API")
    Rel(ra, СИЖ, "Использует", "Java API")
}

Rel(ИИ, СПС, "Получает событие", "gRPC")
Rel(КУ, ШУ, "Отправляет уведомление")
Rel_D(КИБС, БС, "отправляет событие для синхронизации с ЦС")
Rel(GW, ra, "Запрос на изменение информации о животных", "REST")
@enduml