@startuml C1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' === Участники ===
Person(оператор, "Оператор", "Получает оповещения от системы, связывается с нужными сотрудниками для решения возникающих проблем")
Person(управляющий, "Управляющий", "")

' === Системы ===
Enterprise_Boundary(агент, "Агент мониторинга и автоматизации") {
    System(GW, "API шлюз")
    System(АС, "Аггрегатор событий")
    System(ПМА, "Подсистема мониторинга и автоматизации (ПМА)", "Отвечает за постоянный мониторинг стада, автоматизацию кормления")
    System(IoT, "IoT Подсистема")
}
System(ЦС, "Центральный сервер (ЦС)")
System_Ext(MWA, "Мобильное/Web приложение")

' === Взаимосвязи ===
Rel(ПМА, оператор, "Оповещает об отклонениях в поведении животных, изменении их состоянии, количества")
Rel(IoT, оператор, "Оповещает о неисправности оборудования")
Rel(АС, GW, "Периодически синхронизирует данные c ЦС")
Rel(ПМА, АС, "Сохраняет события для синхронизации с ЦС")
Rel(GW, ЦС, "передает данные в ЦС")
Rel(GW, ПМА, "перенаправляет вызовы в ПМА")
Rel(управляющий, GW, "Изменяет рацион животных, обновляет данные о запасах корма, вносит данные о животных")
Rel(управляющий, ЦС, "редактирует метрики, получает значения метрик")
Rel(MWA, GW, "Получает доступ через API")
Rel(IoT, ПМА, "Передает данные с систем наблюдения, а также данные о состоянии оборудования")
Rel(ПМА, IoT, "Изменяет режим кормления")
@enduml