@startuml C1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' === Участники ===
Person(оператор, "Оператор", "Получает оповещения от системы, связывается с нужными сотрудниками для решения возникающих проблем")
Person(управляющий, "Управляющий", "")

' === Системы ===
Enterprise_Boundary(ЦС, "Центральный сервер") {
    System(ПМА, "Подсистема мониторинга и автоматизации (ПМА)", "Отвечает за постоянный мониторинг стада, автоматизацию кормления")
    System_Ext(ПА, "Подсистема аналитики (ПА)")
}
Enterprise_Boundary(агент, "Агент мониторинга и автоматизации") {
    System(IoT, "IoT Подсистема")
}
System_Ext(MWA, "Мобильное/Web приложение")

' === Взаимосвязи ===
Rel(ПМА, оператор, "Оповещает об отклонениях в поведении животных, изменении их состоянии, количества/о неисправности оборудования")
Rel(ПМА, ПА, "Синхронизирует данные c ПА")
Rel(управляющий, ПМА, "Изменяет рацион животных, обновляет данные о запасах корма, вносит данные о животных")
Rel(управляющий, ПА, "редактирует метрики, получает значения метрик")
Rel(MWA, ПМА, "Получает доступ через API")
Rel(IoT, ПМА, "Передает данные с систем наблюдения, а также данные о состоянии оборудования")
Rel(ПМА, IoT, "Изменяет режим кормления")
@enduml