@startuml Архитектура_система_мониторинга_свиноферм

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_TOP_DOWN()
' === Участники ===
Person(оператор, "Оператор", "")
Person(управляющий, "Управляющий", "")
Enterprise_Boundary(платформа, "Платформа мониторинга свиноферм") {
    System_Boundary(ЦС, "Центральный сервер") {
        Container(ПАУ, "Подсистема авторизации/аутентификации", "Keycloak")
        Container_Boundary(ПА, "Подсистема аналитики (ПА)") {
            Container(МА, "Модуль аналитики (МА)", "Python", "Расчитывает базовые метрики для каждой фермы, позволяет редактировать метрики")
            ContainerDb(dwh, "Data Warehouse", "ClickHouse", "Агрегирует данные с разных ферм, для вычисления различных метрик")
        }
    }
    System_Boundary(агент, "Агент мониторинга и автоматизации") {
        Container(GW, "API Шлюз", "Envoy")
        Container_Boundary(ПМА, "Подсистема мониторинга и автоматизации (ПМА)") {
            Container(МНЖ, "Модуль наблюдения за животными (МНЖ)", "Java")
            Container(ИИ, "Модуль ИИ")
            Container(МАК, "Модуль автоматизации кормления (МАК)", "Java")
            ContainerDb(ПМА_БД, "База данных ПМА", "postgeSQL")
        }
        Container_Boundary(ПАС, "Агрегатор событий") {
            Container(АС, "Агрегатор событий", "Java", "Хранит исходящие события до момента синхронизации с центральным сервером")
            ContainerDb(ПАС_БД, "Хранилище исходящих событий", "postgeSQL")
        }
        Container(ШУ, "Шлюз уведомлений (ШУ)")
        Container(БС, "Брокер сообщений (БС)", "RabbitMQ")
        Container_Boundary(iot_платформа, "IoT подсистема") {
            Container(iot_шлюз, "IoT шлюз", "Node-RED", "Управление кормушками и поилками, получение данных с камер видеонаблюдения, опрос состояния IoT устройств")
            Container(КВН, "Камеры видеонаблюдения")
            Container(ДСФВ, "Датчики систем фильтрации воды")
            Container(КИП, "Кормушки и поилки")
        }
    }
}
' == IoT подсистема ==
Rel(iot_шлюз, КИП, "Отправляет команду выдать корм животным, запрашивает состояние устройств", "LoRaWAN")
Rel(iot_шлюз, ДСФВ, "Запрашивает состояние устройств", "LoRaWAN")
Rel_D(iot_шлюз, ИИ, "Передает данные видеонаблюдения", "LTE/WI-FI")
Rel(iot_шлюз, БС, "Передает данные о состоянии IoT устройств", "MQTT")
Rel_D(КВН, iot_шлюз, "Передает данные видеонаблюдения", "LAN")
Rel(БС, iot_шлюз, "Передает команду изменить режим кормления", "MQTT")

' == Подсистема мониторинга и автоматизации ==
Rel(ИИ, МНЖ, "генерирует события", "gRPC")
Rel(МНЖ, "ШУ", "посылает уведомление", "gRPC")
Rel_U(МНЖ, БС, "синхронизация событий с центральным сервером", "MQTT")
Rel_D(БС, МНЖ, "обновить данные о животных", "MQTT")
Rel_L(МНЖ, ПМА_БД, "Использует", "SQL")
Rel_U(МАК, БС, "Передает команду изменить режим кормления ПМАв IoT шлюз", "MQTT")
Rel(МАК, ШУ, "Посылает уведомление", "gRPC")
Rel_U(МАК, БС, "синхронизация событий с центральным сервером", "MQTT")
Rel_R(МАК, ПМА_БД, "Использует", "SQL")
Rel_D(АС, GW, "синхронизация событий с центральным сервером", "MQTT")

' == Входящие запросы через API Шлюз ==
Rel(управляющий, GW, "Изменяет рацион животных, обновляет данные о запасах корма, вносит данные о животных", "REST")
Rel_L(GW, БС, "перенаправляет входящие запросы", "REST")

' == Исходящие запросы через API Шлюз ==
Rel(GW, dwh, "синхронизирует данные с центральным сервером", "REST")

' == Другое ==
Rel_D(ШУ, управляющий, "Посылает уведомление", "LAN мессенджер")
Rel(ШУ, оператор, "Посылает уведомление", "LAN мессенджер")
Rel(БС, АС, "Накапливает события перед отправкой на ЦС", "MQTT")

Rel_L(управляющий, ПАУ, "авторизации/аутентификации", "REST")
Rel_R(оператор, ПАУ, "авторизации/аутентификации", "REST")
Rel_U(управляющий, МА, "Получение значений, редактирование метрик", "REST")
Rel_L(МА, dwh, "Использует", "SQL")
Rel_L(АС, ПАС_БД, "Использует", "SQL")
@enduml